version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - your-network

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - your-network

networks:
  your-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local