spring:
  application:
    name: demo
  datasource:
    url: ${JWT_URL}
    username: ${JWT_USERNAME}
    password: ${JWT_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration: 604800000
  refresh-token-expiration: 2592000000
server:
  port: 8081